name: Build and Deploy

on:
  push:
    branches:
      - main # Change this to your default branch name (e.g., master)

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧 # This example uses npm
        run: |
          npm install
          npm run build-pages
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # The folder the action should deploy.
          branch: gh-pages # The branch the action should deploy to.
